name: Release
run-name: "Testing release workflow"

env:
  APPLICATION: "test-app"
  GOLANG_BUILDER_VERSION: "1.22-bookworm"
  TARGET_BASE_VERSION: "bookworm-20240722"
  PACKAGE_NAME: "github.com/erigontech/erigon"
  DOCKERHUB_REPOSITORY: "erigontech/dev-erigon"
  BUILD_TAGS: "nosqlite,noboltdb,nosilkworm"
  VERSION: "2.65.4"
  VERSION_TMP: ".."

on:
  push:
    #branches-ignore:
    #  - '**'
    #branches:
    #  - 'master'
    #tags:
      ## only trigger on release tags:
      #- 'v*.*.*'
      #- 'v*.*.*-*'
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: 'Release version number (v#.#.#) which will be used to checkout branch'
      dry_run:
        required: true
        type: boolean
        description: 'When dry_run=true no artifacts would be published and release notes draft only will be prepared'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
    steps:
      - name: Debug
        run: |
          echo The value of dry_run is ${{ inputs.dry_run}} and the value of the release_version is ${{ inputs.release_version }}
          