name: Testing docker multiplatform builds
run-name: Testing docker multiplatform builds

on:
  workflow_dispatch:

jobs:

  build-architecture:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    strategy:
      matrix:
        - runner: ubuntu-24.04-arm
          arch: arm64
        - runner: ubuntu-24.04
          arch: amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_USERNAME }}
        password: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image for ${{ matrix.arch }}
      run: |
        docker buildx build \
            --sbom=true \
            --attest type=provenance,mode=max \
            --push --platform linux/${{ matrix.arch }} \
            --progress plain \
            -t erigontech/dev-erigon:test-oleksandr-${{ matrix.arch }} -f Dockerfile-mp .

      
