name: Testing dockerhub api
run-name: "Testing dockerhub api"

on:
  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Run curl query
        env:
          username: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_USERNAME }}
          password: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_TOKEN }}
        run: |
          echo "JQ version:"
          jq --version
          echo 
          curl -s -H "Authorization: JWT ${password}" 'https://hub.docker.com/v2/namespaces/erigontech/repositories/erigon/tags?page=1&page_size=100' | jq -r '.results|.[]|.name + " " + .tag_last_pushed'

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: ${{ contains(fromJSON('[
            "refs/heads/release/2.60",
            "refs/heads/release/2.61",
            "refs/heads/main"
            ]'), github.ref) }}
  