name: Testing cancel in progress
run-name: "Testing cancel in progress"
# change44466

on:
    push:
        branches:
        - '**'
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}
    ### cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    cancel-in-progress: ${{ !contains(fromJSON('[
            "refs/heads/release/3.4.5",
            "refs/heads/release/5.6.7",
            "refs/heads/main"
        ]'), github.ref) }}

jobs:

  Build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:

      - name: Run 5 min step
        run: |
            echo github_ref=${GITHUB_REF}
            echo DEBUG - environment variables:
            set
            echo Sleeping 5 mins
            sleep 300