name: Testing cancel in progress
run-name: "Testing cancel in progress"
# change1

on:
    push:
        branches:
        - '**'
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}
    ### cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    cancel-in-progress: ${{ contains(fromJSON('["refs/heads/release", "refs/heads/main"]'), github.event_name) }}    

jobs:

  Build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:

      - name: Run 5 min step
        run: |
            echo github_ref=${GITHUB_REF}
            echo DEBUG - environment variables:
            set
            echo Sleeping 5 mins
            sleep 300