name: Release
run-name: "Testing release workflow"

env:
  APPLICATION: "test-app"
  GOLANG_BUILDER_VERSION: "1.22-bookworm"
  TARGET_BASE_VERSION: "bookworm-20240722"
  PACKAGE_NAME: "github.com/erigontech/erigon"
  DOCKERHUB_REPOSITORY: "erigontech/dev-erigon"
  BUILD_TAGS: "nosqlite,noboltdb,nosilkworm"
  VERSION: "2.65.4"
  VERSION_TMP: ".."

on:
  push:
    #branches-ignore:
    #  - '**'
    #branches:
    #  - 'master'
    #tags:
      ## only trigger on release tags:
      #- 'v*.*.*'
      #- 'v*.*.*-*'
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: 'Release version number (v#.#.#) which will be used to checkout branch'
      dry_run:
        required: true
        type: boolean
        description: 'dry_run: when dry_run is set then no artifacts are published and only a draft of the release notes created'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug
        run: |
          echo The value of dry_run is ${{ inputs.dry_run}} and the value of the release_version is ${{ inputs.release_version }}
      
      - name: Build binary
        run: |
          #docker run --platform ${{ matrix.arch }} --rm -e GOOS=${{ matrix.goos }} -e GOARCH=${{ matrix.goarch }} -e CC=${{ matrix.flags_cc }} -e CXX=${{ matrix.flags_cxx }} -w /erigon -v $(pwd):/erigon -v $(pwd)/${{ matrix.build_dst }}:/erigon/build/bin golang:${{ env.GOLANG_BUILDER_VERSION }} make
          docker run --rm -e GOOS=linux -e GOARCH=amd64 -w /app1 -v $(pwd):/app1 golang:bookworm /bin/bash -c "ls -l; cd src; go build main.go; ls -lao "