name: testing-vars
run-name: Testing variables workflow. The value of skip_tests=${{ inputs.skip_tests }}

env:
  APPLICATION: "erigon"
  BUILDER_IMAGE: "golang:1.22-bookworm"
  TARGET_BASE_IMAGE: "alpine:3.20.1"
  APP_REPO: "erigontech/erigon"
  CHECKOUT_REF: "main"
  DOCKER_URL: "erigontech/dev22-erigon"
  DOCKERHUB_REPOSITORY: "erigontech/dev-erigon"
  LABEL_DESCRIPTION: "[docker image built on a last commit id from the main branch] Erigon is an implementation of Ethereum (execution layer with embeddable consensus layer), on the efficiency frontier. Archive Node by default."

on:
  push:
    branches:
      - 'main'
    #tags:
      ## only trigger on release tags:
      #- 'v*.*.*'
      #- 'v*.*.*-*'
  workflow_dispatch:
    inputs:
      skip_tests:
        required: false
        type: boolean
        default: false
        description: 'Skip tests during release build'

jobs:

  Build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5
    strategy:
      matrix:
        runner: [ubuntu-24.04-arm, ubuntu-24.04]

    steps:
      - name: "Debug output - ${{ inputs.skip_tests == 'false' && format('{0}{1}{2}', 'Input variable skip_tests ', ' set to value ', inputs.skip_tests) || inputs.skip_tests }}"
        run: |
          echo "Running on ARCH=$(uname -p)"
          echo
          echo "Env variables:"
          export
          
