name: Release
run-name: Build release ${{ inputs.release_version}} from branch ${{ inputs.checkout_ref }} by @${{ github.actor }}

env:
  APPLICATION: "erigon"
  APPLICATION_VERSION: "Erigon3"
  TEST_TRACKING_TIME_SECONDS: 7200 # 2 hours
  TEST_TOTAL_TIME_SECONDS: 432000   # 5 days
  TEST_CHAIN: "mainnet"
  BUILDER_IMAGE: "golang:1.22-bookworm"
  DOCKER_BASE_IMAGE: "debian:12-slim"
  APP_REPO: "erigontech/erigon"
  PACKAGE: "github.com/erigontech/erigon"
  DOCKERHUB_REPOSITORY: "erigontech/erigon"
  DOCKERFILE_PATH: "Dockerfile.release"
  LABEL_DESCRIPTION: "Erigon is an implementation of Ethereum (execution layer with embeddable consensus layer), on the efficiency frontier. Archive Node by default."

on:
  workflow_dispatch:
    inputs:
      checkout_ref:
        required: true
        type: string
        default: 'main'
        description: 'The branch to checkout and build artifacts from. By default "main".'
      release_version:
        required: true
        type: string
        description: 'Release version number (Pattern - v#.#.# , f.e. v2.60.1 or v3.0.0 or v3.0.0-alpha1 for pre-releases. Use prefix "v".)'
      perform_release:
        required: false
        type: boolean
        default: false
        description: 'perform_release: when set then all artifacts will be published and the DRAFT of the release notes will be created.'
      publish_latest_tag:
        required: false
        type: boolean
        default: false
        description: 'publish_latest_tag: when set then docker image with tag :latest will be also published'

jobs:

  build-release:
    runs-on: [self-hosted, devops-01-Linux]
    #runs-on: ubuntu-latest
    #runs-on: ubuntu-latest-devops-xxlarge
    timeout-minutes: 75
    name: Create git tag, build and publish Release Artifacts
    outputs:
      commit-id: ${{ steps.getCommitId.outputs.id }}
      short-commit-id: ${{ steps.getCommitId.outputs.short_commit_id }}
      application: ${{ env.APPLICATION }}
      parsed-version: ${{ steps.getCommitId.outputs.parsed_version}}

    steps:

      - name: Cleanup working directory
        run: rm -drfv *

      - name: Checkout git repository ${{ env.APP_REPO }} reference ${{ inputs.checkout_ref }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 ## 4.1.7 release
        with:
          repository: ${{ env.APP_REPO }}
          fetch-depth: 0
          ref: ${{ inputs.checkout_ref }}
          path: 'erigon'

      - name: Check if tag ${{ inputs.release_version }} already exists and create it in case perform_release is set.
        if: ${{ (inputs.perform_release) && (inputs.release_version != '') }}
        run: |
          cd erigon
          if git ls-remote --exit-code --quiet --tags origin '${{ inputs.release_version }}'; then
            echo "ERROR: tag ${{ inputs.release_version }} exists and workflow is performing release. Exit."
            exit 1
          else
            echo "OK: tag ${{ inputs.release_version }} does not exists. Proceeding."
            git tag ${{ inputs.release_version }}
            git push origin ${{ inputs.release_version }}
            echo; echo "Git TAG ${{ inputs.release_version }} created and pushed."
          fi

      - name: Run some commands, get commit id
        id: getCommitId
        run: |
          mkdir $GITHUB_WORKSPACE/build-arm64 $GITHUB_WORKSPACE/build-amd64 $GITHUB_WORKSPACE/build-amd64v2
          cd erigon;
          echo DEBUG111
          id
          echo END DEBUG
          echo "id=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short_commit_id=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
          echo "parsed_version=$(echo ${{ inputs.release_version }} | sed -e 's/^v//g')" >> $GITHUB_OUTPUT
          echo "week_of_the_year=$(/bin/date -u "+%Y-%W")" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  ## v3.3.0
        with:
          username: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_USERNAME }}
          password: ${{ secrets.ORG_DOCKERHUB_ERIGONTECH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf ## v3.2.0

      - name: Set up Docker Buildx
        ## uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db ## v3.6.1
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/amd64/v2,linux/arm64

      - name: Setup GO build and pkg cache for one week only
        id: cache
        uses: actions/cache@v4
        with:
          key: cache-year-week-${{ steps.getCommitId.outputs.week_of_the_year }}-go.mod-hash:${{ hashFiles('erigon/go.mod') }}
          path: |
            ~/go/pkg
            ~/.cache

      - name: Build for linux/arm64
        #if: 3 > 5
        run: >
          docker run --platform linux/arm64
          --rm
          -v $(pwd)/erigon:/erigon:ro
          -v ${GITHUB_WORKSPACE}/build-arm64:/erigon-build
          -v ${HOME}/.cache:/root/.cache
          -v ${HOME}/go/pkg/mod:/go/pkg/mod
          -w /erigon --entrypoint /bin/bash
          ${{ env.BUILDER_IMAGE }}
          -c "git config --global --add safe.directory /erigon;
          make GOARCH=arm64 GOBIN=/erigon-build BUILD_TAGS=nosqlite,noboltdb,nosilkworm 
          erigon downloader devnet evm caplin diag integration rpcdaemon sentry txpool"

        ## temporary disable silkworm in 3.x.x
      - name: Build for linux/amd64 (with nosilkworm tag)
        run: >
          docker run --platform linux/amd64
          --rm
          -v $(pwd)/erigon:/erigon:ro
          -v ${GITHUB_WORKSPACE}/build-amd64:/erigon-build
          -v ${HOME}/.cache:/root/.cache
          -v ${HOME}/go/pkg/mod:/go/pkg/mod
          -w /erigon --entrypoint /bin/bash
          ${{ env.BUILDER_IMAGE }}
          -c "git config --global --add safe.directory /erigon;
          make GOARCH=amd64 GOAMD64=v1 GOAMD64_VERSION=v1 GOBIN=/erigon-build BUILD_TAGS=nosqlite,noboltdb,nosilkworm 
          erigon downloader devnet evm caplin diag integration rpcdaemon sentry txpool;
          if [ ${WITH_SILKWORM} ]; then find / -name libsilkworm_capi.so -exec install {} /erigon-build \; ; fi;"

        ## temporary disable silkworm in 3.x.x
      - name: Build for linux/amd64/v2 (with nosilkworm tag)
        run: >
          docker run --platform linux/amd64/v2
          --rm
          -v $(pwd)/erigon:/erigon:ro
          -v ${GITHUB_WORKSPACE}/build-amd64v2:/erigon-build
          -v ${HOME}/.cache:/root/.cache
          -v ${HOME}/go/pkg/mod:/go/pkg/mod
          -w /erigon --entrypoint /bin/bash
          ${{ env.BUILDER_IMAGE }}
          -c "git config --global --add safe.directory /erigon;
          make GOARCH=amd64 GOAMD64=v2 GOBIN=/erigon-build BUILD_TAGS=nosqlite,noboltdb,nosilkworm 
          erigon downloader devnet evm caplin diag integration rpcdaemon sentry txpool;
          if [ ${WITH_SILKWORM} ]; then find / -name libsilkworm_capi.so -exec install {} /erigon-build \; ; fi;"

      - name: Create archives and checksums
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir $GITHUB_WORKSPACE/release
          for dir in build-*; do
            cd $dir
            echo Current directory is $(pwd) . Checksum file and archive will be created for this directory
            sha256sum * > checksums.txt
            tar czvf $GITHUB_WORKSPACE/release/${APPLICATION}_${RELEASE_VERSION}_linux_$(echo $dir | sed 's,build-,,').tar.gz \
              --transform "s,^./,${APPLICATION}_${RELEASE_VERSION}_linux_$(echo $dir | sed 's,build-,,')/," .
            cd -
          done
          cd $GITHUB_WORKSPACE/release
          sha256sum * > ${APPLICATION}_${RELEASE_VERSION}_checksums.txt
          echo Content of release directory:
          find . -type f -ls

      - name: Upload artifact -- linux/arm64
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a  ## v4.3.6
        with:
          name: ${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_arm64.tar.gz
          path: ${{ github.workspace }}/release/${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_arm64.tar.gz
          retention-days: 3
          compression-level: 0
          if-no-files-found: error

      - name: Upload artifact -- linux/amd64
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a  ## v4.3.6
        with:
          name: ${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_amd64.tar.gz
          path: ${{ github.workspace }}/release/${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_amd64.tar.gz
          retention-days: 3
          compression-level: 0
          if-no-files-found: error

      - name: Upload artifact -- linux/amd64/v2
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a  ## v4.3.6
        with:
          name: ${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_amd64v2.tar.gz
          path: ${{ github.workspace }}/release/${{ env.APPLICATION }}_${{ inputs.release_version }}_linux_amd64v2.tar.gz
          retention-days: 3
          compression-level: 0
          if-no-files-found: error

      - name: Cleanup working directory
        run: rm -drfv *
